# Generated by Django 3.2.6 on 2021-08-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creator',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
