# Generated by Django 3.2.6 on 2021-08-31 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_book_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cre',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
